version: "3.9"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  fastapi_app:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  postgres_data: