"""Add completed flag to Note

Revision ID: 4fb6a495963c
Revises: 1474d9641be7
Create Date: 2025-07-11 17:43:47.607797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb6a495963c'
down_revision: Union[str, Sequence[str], None] = '1474d9641be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('is_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'is_completed')
    # ### end Alembic commands ###
